/**:
  ros__parameters:
    vehicle:
      cg_to_front_m: 1.228
      cg_to_rear_m: 1.5618
      front_corner_stiffness: 0.1
      rear_corner_stiffness: 0.1
      mass_kg: 1500.0
      yaw_inertia_kgm2: 12.0
      width_m: 1.83
      front_overhang_m: 1.0
      rear_overhang_m: 1.03
 